# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mopub.ObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mopub.ObjectiveC
  pod 'mopub-ios-sdk', '5.10'

end
