source 'https://github.com/CocoaPods/Specs'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'mopub.ObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mopub.ObjectiveC
  pod 'mopub-ios-sdk', '~> 5.17.0'
end
